
const string DB_GENERATE_ID = "_id"

const string REWARDS_CODE_CHECKIN = "checkin"
const string REWARDS_CODE_REGISTER = "register"
const string REWARDS_CODE_VERIFY = "verify"
const string REWARDS_CODE_REFERRAL = "referral"
const string REWARDS_CODE_INVITED = "invited"
const string REWARDS_CODE_REVIEW = "review"
const string REWARDS_CODE_DRAW = "draw"
const string REWARDS_CODE_VERIFY_EMAIL = "verify-email"

// Common Setting
const i32 REGION_BD = 1
const i32 REGION_CN = 2
const i32 REGION_MM = 3
const i32 REGION_PK = 4
const i32 REGION_JP = 5
const i32 REGION_KE = 6
const string PLATFORM_ANDROID = "Android-App"
const string PLATFORM_IOS = "iOS-App"
const string PLATFORM_H5 = "Mobile-Web"
const string PLATFORM_WEB = "Web"

// Auth Setting
const i16 CONTACT_TYPE_PHONE = 1
const i16 CONTACT_TYPE_EMAIL = 2
const i16 CONTACT_TYPE_FB = 3
const i16 CONTACT_TYPE_ACCOUNT = 4

// 运费策略设置
const string PARAM_MODULE_POSTAGE_STRATEGY = 'postage-strategy'
const string PARAM_PS_TYPE = 'PS_TYPE'  // 运费策略类型，1:分别策略 2:明细策略
const string PARAM_PS_PLATFORM_SHIP_PLATFORM_CHARGES = 'PS_PLATFORM_SHIP_PLATFORM_CHARGES'  // 非自发货店铺订单在用户订单批次中统收一次运费
const string PARAM_PS_TYPE_OF_SELLER_SHIP = 'PS_TYPE_OF_SELLER_SHIP'  // 本地自发货店铺运费类型，1:店铺设置 2:平台定义
const string PARAM_PS_SELLER_SHIP_PLATFORM_SPECIFIED = 'PS_SELLER_SHIP_PLATFORM_SPECIFIED'  // 本地自发货店铺运费中平台定义费用
const string PARAM_PS_TYPE_OF_CHINESE_ORDER = 'PS_TYPE_OF_CHINESE_ORDER'  // 中国发货订单运费收取类型，1:店铺设置 2:平台统收
const string PARAM_PS_CHINESE_ORDER_PLATFORM_CHARGES = 'PS_CHINESE_ORDER_PLATFORM_CHARGES'  // 中国发货订单运费中平台统收费用
const string PARAM_PS_TYPE_OF_SELLER_LOCAL_SHIP = 'PS_TYPE_OF_SELLER_LOCAL_SHIP'  // 本地自发货店铺运费类型，1:店铺设置 2:平台定义
const string PARAM_PS_SELLER_LOCAL_SHIP_PLATFORM_SPECIFIED = 'PS_SELLER_LOCAL_SHIP_PLATFORM_SPECIFIED'  // 本地自发货店铺运费中平台定义费用
const string PARAM_PS_TYPE_OF_PLATFORM_LOCAL_SHIP = 'PS_TYPE_OF_PLATFORM_LOCAL_SHIP'  // 本地非自发货店铺运费类型，1:店铺设置 2:平台定义
const string PARAM_PS_PLATFORM_LOCAL_SHIP_PLATFORM_CHARGES = 'PS_PLATFORM_LOCAL_SHIP_PLATFORM_CHARGES'  // 本地非自发货店铺运费中平台统收费用
const string PARAM_PS_TYPE_OF_LOCAL_WAREHOUSE_AGENT = 'PS_TYPE_OF_LOCAL_WAREHOUSE_AGENT'  // 本地仓代运营商品运费类型，1:店铺设置 2:平台定义
const string PARAM_PS_LOCAL_WAREHOUSE_AGENT_PLATFORM_CHARGES = 'PS_LOCAL_WAREHOUSE_AGENT_PLATFORM_CHARGES'  // 本地仓代运营商品运费中平台统收费用

const string PARAMETER_MODULE_REDEEM = "redeem"
const string PARAMETER_REDEEM_ENABLE = "REDEEM_ENABLE"
const string PARAMETER_REDEEM_MIN_USE_COIN = "REDEEM_MIN_USE_COIN"
const string PARAMETER_REDEEM_AMOUNT_PERCENT = "REDEEM_AMOUNT_PERCENT"
const string PARAMETER_REDEEM_MAX_USE_COIN = "REDEEM_MAX_USE_COIN"
const string PARAMETER_REDEEM_RATIO_CURRENCY = "REDEEM_RATIO_CURRENCY"
const string PARAMETER_REDEEM_RATIO_COIN = "REDEEM_RATIO_COIN"
const string PARAMETER_REDEEM_ENABLE_IN_WAP = "REDEEM_ENABLE_IN_WAP"

const string PARAMETER_MODULE_ORDER = "order"
const string PARAMETER_ORDER_COD_ENABLE = "ORDER_COD_ENABLE"
const string PARAMETER_ORDER_MUST_VERIFIED = "ORDER_MUST_VERIFIED"
const string PARAMETER_ORDER_ONLINE_ENABLE = "ORDER_ONLINE_ENABLE"
const string PARAM_ORDER_STORE_COMMISSION_RATE = "store_commission_rate"
const string PARAM_ORDER_PAY_GATEWAY_FEE_RATE  = "pay_gateway_fee_rate"
const string PARAM_ORDER_OPERATION_FEE  = "order_operation_fee"
const string PARAM_ORDER_FREIGHT_SETTLEMENT  = "freight_settlement"
const string PARAM_ORDER_LIQUIDATION_SETTINGS  = "liquidation_settings"
const string PARAM_MODULE_PREPAYMENT = "prepayment"

const string PARAM_MODULE_POSTAGE_DISCOUNT = "postage_discount"
const string PARAM_PD_ONLINE_REMISSION_ENABLE = "POSTAGE_ONLINE_REMISSION_ENABLE"
const string PARAM_PD_ONLINE_REMISSION_LIMIT = "POSTAGE_ONLINE_REMISSION_LIMIT"
const string PARAM_PD_REMISSION_NOTIFY_ENABLE = "POSTAGE_REMISSION_NOTIFY_ENABLE"
const string PARAM_PD_ONLINE_DISCOUNT = "POSTAGE_ONLINE_DISCOUNT"
const string PARAM_PD_COD_DISCOUNT = "POSTAGE_COD_DISCOUNT"
const string PARAM_PD_REMISSION_NOTIFY = "POSTAGE_REMISSION_NOTIFY"

const string PARAMETER_MODULE_PROMOTION = "promotion"
const string GROUP_BUYING_LIMIT_STORE_TYPE = "GROUP_BUYING_LIMIT_STORE_TYPE"
const string GROUP_BUYING_LIMIT_STORE_IDS = "GROUP_BUYING_LIMIT_STORE_IDS"
const string GROUP_BUYING_VALIDITY_PERIOD = "GROUP_BUYING_VALIDITY_PERIOD"
const string GROUP_BUYING_COMPLETION_PERIOD_HOURS = "GROUP_BUYING_COMPLETION_PERIOD_HOURS"
const string GROUP_BUYING_BUYERS_GOALS = "GROUP_BUYING_BUYERS_GOALS"
const string GROUP_BUYING_ROBOT_ENABLE = "GROUP_BUYING_ROBOT_ENABLE"
const string GROUP_BUYING_TAG_ENABLE = "GROUP_BUYING_TAG_ENABLE"
const string GROUP_BUYING_TAG_OTHERS_ENABLE = "GROUP_BUYING_TAG_OTHERS_ENABLE"


const string SPEND_CODE_REDEEM_ORDER = "redeem-order"
const string SPEND_CODE_REFUND_ORDER = "refund-order"

// Language code and name mapping
const map<string, string> LANGUAGES = {
    "en": "English",
    "bn": "Bengal"
}

// Error codes in each service.
// [1000-1999] System level general error code
const i16 ERROR_SYS_DB = 1000
const i16 ERROR_SYS_TOKEN_INVALID = 1001
const i16 ERROR_SYS_TOKEN_EXPIRED = 1002
const i16 ERROR_SYS_UNAUTHORIZED = 1003
const i16 ERROR_SYS_REFRESH_TOKEN_EXPIRED = 1006
const i16 ERROR_SYS_OUT_OF_RANGE = 1007
const i16 ERROR_SYS_DB_TRANACTION_FAILED_MAX_RETRY = 1008
const i16 ERROR_SYS_RESOURCE_EXPIRED = 1009

// [2000-2999] Common service
const i16 ERROR_COMMON_REGION_NONEXISTENT = 2100
const i16 ERROR_COMMON_STATE_NONEXISTENT = 2101
const i16 ERROR_COMMON_STATE_NOTIN_REGION = 2102
const i16 ERROR_COMMON_CITY_NONEXISTENT = 2103
const i16 ERROR_COMMON_AREA_NONEXISTENT = 2104
const i16 ERROR_COMMON_CITY_NOTIN_REGION = 2105
const i16 ERROR_COMMON_SMS_RESEND = 2202
const i16 ERROR_COMMON_PHONE_ABNORMAL = 2203
const i16 ERROR_COMMON_EMAIL_INVALID = 2204
const i16 ERROR_COMMON_EMAIL_SEND_FAILED = 2205
const i16 ERROR_COMMON_EMAIL_ABNORMAL = 2206
const i16 ERROR_COMMON_EMAIL_RESEND = 2207
const i16 ERROR_COMMON_CODE_EXPIRED = 2250
const i16 ERROR_COMMON_CODE_INVALID = 2251
const i16 ERROR_COMMON_SEND_FAILED = 2252
const i16 ERROR_COMMON_BANNER_NONEXISTENT = 2253
const i16 ERROR_COMMON_BANNER_INDEX_EXPIRED = 2254
const i16 ERROR_COMMON_POPUPADS_NOT_FOUND = 2256
const i16 ERROR_COMMON_STARTUPIMAGE_NOT_FOUND = 2257
const i16 ERROR_COMMON_SHORTCUT_OUTNUMBER = 2258
const i16 ERROR_COMMON_SPECIAL_NOTFOUND = 2259
const i16 ERROR_COMMON_SPECIAL_EXISTS = 2260
const i16 ERROR_COMMON_ADDRESS_METHOD_EXISTS = 2261
const i16 ERROR_COMMON_POSTCODE_EXISTS = 2262
const i16 ERROR_COMMON_IMG_CAPTCHA_INVALID = 2263

// [3000-3999] Account and authentication service
const i16 ERROR_AUTH_PASSWORD_INVALID = 3003
const i16 ERROR_AUTH_ACCOUNT_NOT_EXIST = 3004
const i16 ERROR_AUTH_ACCOUNT_NAME_EXISTED = 3005
const i16 ERROR_AUTH_FACEBOOK_ACCOUNT_INVALID = 3006
const i16 ERROR_AUTH_FACEBOOK_CONNECT_ERROR = 3007
const i16 ERROR_AUTH_FACEBOOK_NOT_EXISTED = 3008
const i16 ERROR_AUTH_FACEBOOK_ACCOUNT_EXISTED = 3009
const i16 ERROR_AUTH_ACCOUNT_FACEBOOK_EXISTED = 3010
const i16 ERROR_AUTH_ACCOUNT_DISABLED= 3011
const i16 ERROR_AUTH_CONTACT_NOT_EXIST = 3012
const i16 ERROR_AUTH_PASSWORD_SETTED = 3013
const i16 ERROR_AUTH_ACCOUNT_KBZ_EXISTED = 3014


// [4000-5999] Member service
const i16 ERROR_MEMBER_ADDRESS_NONEXISTENT = 4050
const i16 ERROR_MEMBER_REWARD_NODE_CODE_INVALID = 4500
const i16 ERROR_MEMBER_REWARD_GOT = 4501
const i16 ERROR_MEMBER_INVITE_CODE_INVALID = 4502
const i16 ERROR_MEMBER_INVITE_NOT_FOUND = 4503
const i16 ERROR_MEMBER_INVITED = 4504
const i16 ERROR_MEMBER_INVITE_VERIFIED = 4505
const i16 ERROR_MEMBER_INVITE_BALANCE = 4506
const i16 ERROR_MEMBER_BALANCE_NOT_ENOUGH = 4507
const i16 ERROR_MEMBER_DUPLICATE_DEDUCTION = 4508
const i16 ERROR_MEMBER_DUPLICATE_REFUND = 4509

const i16 ERROR_VOUCHER_TEMPLATE_NOT_FOUND = 4510
const i16 ERROR_VOUCHER_TEMPLATE_NOT_ENABLED = 4511
const i16 ERROR_VOUCHER_GEN_NOT_EXIST = 4512
const i16 ERROR_VOUCHER_GEN_INVALID = 4513
const i16 ERROR_VOUCHER_GEN_EXPIRED = 4514
const i16 ERROR_VOUCHER_GEN_RECEIVED = 4515
const i16 ERROR_VOUCHER_ACCOUNT_INVALID = 4516
const i16 ERROR_VOUCHER_NOT_EXIST = 4517
const i16 ERROR_VOUCHER_INVALID = 4518
const i16 ERROR_VOUCHER_EXPIRED = 4519
const i16 ERROR_VOUCHER_NO_MATCH = 4520
const i16 ERROR_VOUCHER_ALL_RECEIVED = 4521
const i16 ERROR_VOUCHER_DIS_DISTRIBUTED = 4522
const i16 ERROR_VOUCHER_DIS_NOT_EXIST = 4523
const i16 ERROR_STORE_FOLLOWED = 4524
const i16 ERROR_STORE_NOT_FOLLOWED = 4525

const i16 ERROR_MEMBER_REFERCODE_EXISTS = 4526
const i16 ERROR_MEMBER_PROMOTER_SOURCE_NOTSUPPORTED = 4527
const i16 ERROR_MEMBER_PROMOTER_DUPLICATE = 4528

const i16 ERROR_VOUCHER_LIMIT_BILL_AMOUNT_INVALID = 4529
const i16 ERROR_VOUCHER_LIMIT_AMOUNT_INVALID = 4529
const i16 ERROR_VOUCHER_GEN_TYPE_INVALID = 4530

// [6000-6999] Good service
const i16 ERROR_LISTING_NOT_FOUND = 6004
const i16 ERROR_CART_ITEM_NOT_FOUND = 6008
const i16 ERROR_CATEGORY_NOT_FOUND = 6010
const i16 ERROR_THING_NOT_FOUND = 6012
const i16 ERROR_SPU_NOT_FOUND = 6013
const i16 ERROR_SPECOFSKU_NOT_FOUND = 6015
const i16 ERROR_TOP_LISTINGS_OVER_LIMIT = 6016
const i16 ERROR_DUPLICATE_KEY_ERROR = 6017
const i16 ERROR_GOODS_NAVITAG_NOT_FOUND = 6018
const i16 INVENTORIES_NOT_FOUND = 6018
const i16 ERROR_GOODS_REVIEW_NOT_EXIST = 6019
const i16 ERROR_GOODS_REVIEW_EXISTED = 6020
const i16 ERROR_GOODS_NOT_COMPLETED = 6021
const i16 ERROR_GOODS_STORE_REVIEW_NOT_EXIST = 6022
const i16 ERROR_DUMMY_WAREHOUSE_APPLYING_EXISTS = 6023
const i16 ERROR_DUMMY_WAREHOUSE_APPLYING_NOT_EXISTS = 6024
const i16 ERROR_STORAGE_WAREHOUSE_APPLYING_NOT_EXISTS = 6025
const i16 ERROR_PROPERTY_VALUE_NEED_SELLER_ID = 6026
const i16 ERROR_PROPERTY_NOT_EXISTS = 6027
const i16 ERROR_LISTING_FULL_EDIT_FAILED = 6028
const i16 ERROR_ARTICLE_NOT_FOUND = 6029
const i16 ERROR_GOODS_PAYMENT_METHOD_INVALID = 6030
const i16 ERROR_GOODS_EXPORT_MODE_INVALID = 6031
const i16 ERROR_GOODS_UPLOAD_FILE_FAILED = 6032
const i16 ERROR_EXPORT_GOODS_IS_NONE = 6033
const i16 ERROR_CREATE_DERIVE_SKU_FAILED = 6034
const i16 ERROR_WAREHOUSE_NOT_EXISTS = 6035
const i16 ERROR_TASK_NOT_COMPLETED = 6036
const i16 ERROR_REQUEST_HW_SERVICE_FAILED = 6037
const i16 ERROR_SELECTIVE_NOT_FOUND = 6038
const i16 ERROR_SELECTIVE_CREATE_FAILED = 6039
const i16 ERROR_SELECTIVE_TYPE_NOT_FOUND = 6040
const i16 ERROR_SELECTIVE_UPDATE_FAILED = 6041
const i16 ERROR_BRAND_INDEX_EXISTS = 6042

// [7000-7999] Order service
const i16 ERROR_PASS_PARAMETER = 7001
const i16 SALEORDER_NOT_FOUND = 7040
const i16 STARTINDEX_PARAM_ERROR = 7041
const i16 ERROR_INPUT_PARAMETER = 7042
const i16 SHIP_ORDER_NOT_FOUND = 7043
const i16 SHIPPACKAGE_NOT_FOUND = 7044
const i16 PARAM_PACKAGE_STATUS_ERROR = 7045
const i16 RECEIVE_AMOUNT_ERROR = 7046
const i16 PARAM_DELIVER_STATUS_ERROR = 7047
const i16 TRADE_SKU_TYPE_ERROR = 7048
const i16 ORDER_LOG_NOT_FOUND = 7049
const i16 ERROR_BILL_NOT_FOUND = 7050
const i16 ERROR_ORDER_PLACE_TOO_SHORT = 7051
const i16 ERROR_PARCEL_LOG_STATUS = 7052
const i16 ERROR_PARCEL_LOG_TYPE = 7053
const i16 ERROR_PARCEL_LOG_NOT_FOUND = 7054
const i16 ERROR_PARCEL_LOG_HAVE_EXISTED = 7055
const i16 ERROR_ECOURIER_PAY_METHOD_NOT_FOUND = 7056
const i16 ERROR_PARCEL_ANONYMOUS_TYPE = 7057
const i16 ERROR_REQUEST_EXCEPTION = 7059
const i16 ERROR_MAPPING_ADDRESS_NOT_FOUND = 7060
const i16 ERROR_ECOURIER_CITY_AND_AREA = 7061
const i16 ERROR_PAY_BILL_NOT_FOUND = 7062
const i16 ERROR_INITIATE_SSL_PAYMENT_FAIL = 7063
const i16 ERROR_HASH_VALIDATION_PARAMS_FAIL = 7064
const i16 ERROR_TRANS_HAVE_PAID = 7065
const string MSG_TRANS_HAVE_PAID = "The order you are paying has been paid."
const i16 ERROR_FIND_TRANS_FAIL = 7066
const i16 ERROR_PAY_TRANS_NOT_FOUND = 7067
const i16 ERROR_SSL_RETURN_DATA = 7068
const i16 ERROR_PAY_VALIDATE_FAIL = 7069
const i16 ERROR_PAY_SESSION_NOT_FOUND = 7070
const i16 ERROR_COLLECTION_NOT_FOUND = 7071
const i16 ERROR_OPERATION_FAILED = 7072
const i16 ERROR_OBJECT_ALREADY_EXISTS = 7073
const i16 ERROR_DOCUMENT_NOT_FOUND = 7074
const i16 ERROR_AGREEMENT_ALREADY_EXISTS = 7075
const i16 ERROR_PAYMENT_INCOMPLETE = 7076
const i16 ERROR_BKASH_RESPONCE = 7077
const i16 ERROR_ORDER_CAN_NOT_CANCEL = 7078
const i16 ERROR_KBZ_REQUEST_FAIL = 7079
const i16 ERROR_PAY_GMO_EXCEPTION = 7080
const i16 ERROR_XED_EXCEPTION = 7081
const i16 ERROR_XED_RESOURCE_NOT_FOUND = 7082

//[10000-10999] Message service
const i16 ERROR_ORDER_SOURCE_TYPE = 10000
const i16 ERROR_TALK_NOT_EXIST = 10001
const i16 ERROR_FIRE_BASE_ERROR = 10002
const i16 ERROR_UMENG_ERROR = 10003

//[11000-11999] Seller Service
const i16 ERROR_SELLER_STORE_NOT_FOUND = 11001
const i16 ERROR_INPUT_PARAM_STORE_TYPE = 11002
const i16 ERROR_INPUT_PARAM_SELLER_TYPE = 11003
const i16 ERROR_INPUT_PARAM_STORE_NAME = 11004
const i16 ERROR_DOCUMENT_NOT_FIND = 11005
const i16 ERROR_PASSWORD_NOT_FOUND = 11006
const i16 ERROR_INPUT_PARAM_LOGIN_TYPE = 11007
const i16 ERROR_INPUT_PARAM_LACK = 11008
const i16 ERROR_STORE_COUNT_LIMIT = 11009
const i16 ERROR_LOGIN_PASSWORD = 11010
const i16 ERROR_PASS_PARAMS = 11011
const i16 ERROR_DUPLICATE_CREATE = 11012
const i16 ERROR_STORE_ACCOUNT_NOT_FOUND = 11013
const i16 ERROR_SELLER_STORE_MESSAGE_NOT_FOUND = 11014


//[12000-12999] Promotion Service
const i16 ERROR_PROMOTION_APPLY_NOT_FOUND = 12000
const i16 ERROR_PROMOTION_SESSION_NOT_FOUND = 12001
const i16 ERROR_PROMOTION_ACTIVITY_SKU_NOT_FOUND = 12002
const i16 ERROR_PROMOTION_ACTIVITY_STOCK_UNAVAILABLE = 12003
const i16 ERROR_PROMOTION_VALID_LUCKY_DRAW_BATCH_NOT_FOUND = 12004
const i16 ERROR_PROMOTION_LUCKY_DRAW_BATCH_CREATE_FAILED = 12005
const i16 ERROR_PROMOTION_LUCKY_DRAW_BATCH_NOT_FOUND = 12006
const i16 ERROR_PROMOTION_LUCKY_DRAW_TIMEOUT = 12007
const i16 ERROR_PROMOTION_LUCKY_DRAW_NOT_START = 12008
const i16 ERROR_PROMOTION_ACTIVITY_EXPIRED = 12009
const i16 ERROR_PROMOTION_ACTIVITY_INVALID = 12010
const i16 ERROR_REDEEM_SKU_NOT_FOUND = 12011
const i16 ERROR_REDEEM_SKU_INVALID = 12012
const i16 ERROR_REDEEM_SKU_STOCK_UNAVAILABLE = 12013
const i16 ERROR_APPLY_STOCK_PRICE_INVALID = 12014
const i16 ERROR_APPLY_SKU_SESSION_APPLIED = 12015
const i16 ERROR_PROMOTION_SESSION_EXPIRED = 12016
const i16 ERROR_ACTIVE_TODAY_DEAL_ALREADY_EXISTS = 12017
const i16 ERROR_TODAY_DEALS_APPLY_FAILED = 12018
const i16 ERROR_TODAY_DEAL_AUDIT_FAILED = 12019
const i16 ERROR_TODAY_DEALS_OFF_FAILED = 12020
const i16 ERROR_TODAY_DEAL_NOT_FOUND = 12021
const i16 ERROR_PROMOTION_NOT_FOUND = 12022
const i16 ERROR_PROMO_PRODUCT_NOT_FOUND = 12023
const i16 ERROR_PROMO_PRODUCT_ALREADY_EXISTS = 12024
const i16 ERROR_PRE_CREATE_GROUP_BUYING_TEAM_FAILED = 12025
const i16 ERROR_GROUP_BUYING_TEAM_NOT_FOUND = 12026
const i16 ERROR_GROUP_BUYING_TEAM_NOT_AVAILABLE = 12027
const i16 ERROR_FAILED_TO_JOIN_GROUP_BUYING_TEAM = 12028
const i16 ERROR_FAILED_TO_START_GROUP_BUYING_TEAM = 12029
const i16 ERROR_FAILED_TO_UPDATE_GROUP_BUYING_TEAM = 12030
const i16 ERROR_FAILED_TO_UPDATE_GROUP_BUYING_TEAM_MEMBER = 12031
const i64 ERROR_GROUP_BUYING_NOT_ACTIVE = 12032
const i16 ERROR_GROUP_BUYING_TAG_NOT_FOUND = 12033
const i16 ERROR_GROUP_BUYING_NOT_FOUND = 12034
const i16 ERROR_GROUP_BUYING_SKU_NOT_IN = 12035
const i16 ERROR_APPLY_BIG_DISCOUNT_SALE_FAILED = 12036
const i16 ERROR_APPLY_BIG_DISCOUNT_SALE_PRODUCTS_FAILED = 12037
const i16 ERROR_BIG_DISCOUNT_SALE_SKU_ALREADY_EXISTS = 12038
const i16 ERROR_PROMO_PRODUCTS_LIMIT = 12039

const i16 ERROR_TOPIC_PAGE_NOT_EXIST = 12100
const i16 ERROR_TOPIC_PAGE_EXISTS = 12101


//[13000-13999] Logistics Service
const i16 ERROR_LOGISTICS_DOCUMENT_NOT_FOUND = 13000
const i16 ERROR_DOCUMENT_HAVE_EXISTS = 13000
const i16 ERROR_EXPRESS_PACKAGE_NOT_FOUND = 13006
const i16 ERROR_EXPRESS_PACKAGE_INVALID_OPT = 13007
const i16 ERROR_LOG_INSERT_FAILD = 13008
const i16 ERROR_DELIVERY_BATCH_NOT_FOUND = 13009
const i16 ERROR_BOX_NOT_FOUND = 13010
const i16 ERROR_BOX_INVALID_OPT = 13011
const i16 ERROR_RECEIPT_DETAIL_EXIST = 13012
const i16 ERROR_RECEIVABLE_NOT_EXIST = 13013
const i16 ERROR_RECEIPT_NOT_EXIST = 13014
const i16 ERROR_RECEIPT_DETAIL_NOT_EXIST = 13015
const i16 ERROR_RECEIPT_DETAIL_NOT_PENDING = 13016
const i16 ERROR_RECEIPT_HAS_COMPLETED = 13017

//[14000-14999] Cube Service
const i16 ERROR_APP_ID_OR_SECRET_INVALID = 14000
const i16 ERROR_OAUTH2_CLIENT_NOT_FOUND = 14001
const i16 ERROR_OAUTH2_CODE_NOT_FOUND = 14002

//[15000-15999] Statistics Service
const i16 ERROR_TOP_TIME_RANGE = 15000
const i16 ERROR_STAT_PASS_PARAMETER = 15001
const i16 ERROR_STAT_DOCUMENT_NOT_FOUND = 15002

//[16000-16999] 第三方 Service
const i16 CODE_OFS_EXCEPTION = 8013
const i16 CODE_OFS_RESOURCE_NOT_FOUND = 8014

// queue name
const string QUEUE_ONLINE_BILL = "onlineOrderQueue"
const string QUEUE_COIN_AND_VOUCHER = "coinAndVoucher"
const string QUEUE_ORDER_NOTIFY = "orderNotify"
const i32 TTL = 172800000
const i32 REVIEW_TTL = 2592000000
const i32 DELAY_30S_TTL = 30000
enum queue_type {
    normal = 1,
    delay = 2
}
// queue action
const string GOODS_ORDER_COMPLETE_NOTICE = "goods_order_complete_notice"
const string GOODS_DELAY_30_CHECK_REVIEW = "goods_delay_30_check_review"
const string ORDER_OUTER_ORDER_CREATE = "order_outer_order_create"
const string ORDER_OUTER_ORDER_SET_PAID = "order_outer_order_set_paid"
const string ORDER_CANCEL_COD_ORDER = "order_cancel_cod_order"
const string ORDER_CANCEL_UNPAY_ONLINE = "order_cancel_unpay_online"
const string ORDER_VIRTUAL_PAYMENT = "order_virtual_payment"
const string ORDER_CANCEL_ROBOT_ORDER = "order_cancel_robot_order"
const string ORDER_CONFIRM_ONLINE_ORDER = "order_confirm_online_order"
const string MEMBER_REVIEW_ADD_COIN_REWARD = "member_review_add_coin_reward"
const string MEMBER_CANCEL_ORDER_RETURN_COIN = "member_cancel_order_return_coin"
const string MEMBER_CANCEL_ORDER_RETURN_VOUCHER = "member_cancel_order_return_voucher"
const string MESSAGE_NOTIFY_ORDER_STATUS_CHANGE = "message_notify_order_status_change"
const string MESSAGE_UPSERT_MESSAGE = "upsert_message"
const string PROMOTION_CANCEL_ORDER_RELEASE_INVENTORY = "promotion_cancel_order_release_inventory"
const string ORDER_SSL_VALIDATE_PAYMENT_WITH_IPN = "order_ssl_validate_payment_with_ipn"
const string ORDER_BATCH_CREATE = "order_batch_create"
const string ORDER_RECEIVE_COMPLETE = "order_receive_complete"
const string ORDER_REJECT_COMPLETE = "order_reject_complete"
const string ORDER_SELLER_REJECT_AFTER_SALE = "order_seller_reject_after_sale"
const string ORDER_CREATE_AFTER_SALE = "order_create_after_sale"
const string ORDER_SALEORDER_PLATFORM_INFO = "order_saleorder_platform_info"
const string ORDER_RECEIVE_PACKAGE = "order_receive_package"
const string ORDER_REFUND_TRANSACTION = "order_refund_transaction"
const string ORDER_CANCEL_GROUP_ORDER = "order_cancel_group_order"
const string ORDER_CANCEL_SALE_ORDER = "order_cancel_sale_order"
const string ORDER_CONFIRM_JUDGE_SHIP = "order_confirm_judge_ship"
const string ORDER_CONFIRM_JUDGE_CANCEL = "order_confirm_judge_cancel"
const string ORDER_SHIP_JUDGE_ARRIVE_TRAN_WAREHOUSE = "order_confirm_judge_arrive_tran_warehouse"
const string ORDER_SHIP_JUDGE_CANCEL = "order_ship_judge_cancel"

const string PHOENIX_CANCEL_ORDER = "phoenix_cancel_order"
const string PHOENIX_PAY_ORDER = "phoenix_pay_order"
const string PHOENIX_CONFIRM_ORDER = "phoenix_confirm_order"
const string PHOENIX_DISPATCH_ORDER = "phoenix_dispatch_order"
const string PHOENIX_COMPLETE_ORDER = "phoenix_complete_order"
const string PHOENIX_REJECT_ORDER = "phoenix_reject_order"

const string PHOENIX_CREATE_INVITED_USER = "phoenix_create_invited_user"
const string PHOENIX_UPDATE_INVITED_USER = "phoenix_update_invited_user"
const string PHOENIX_ORDER_CONVERT = "phoenix_order_convert"
const string PHOENIX_UPDATE_ARTICLE_STATUS = "phoenix_update_article_status"
const string PHOENIX_CREATE_ARTICLE_FROM_REVIEW = "phoenix_create_article_from_review"

const string STATISTICS_SOTRES_MONTHLY_CLEARING = "statistics_stores_monthly_clearing"
const string STATISTICS_ALL_SOTRES_MONTHLY = "statistics_all_stores_monthly"
const string STATISTICS_CONFIRM_CLEARING = "statistics_confirm_clearing"
const string STATISTICS_CLEARING_ORDER_MAIL = "statistics_clearing_order_mail"

const string HW_ADD_USER = "hw_add_user"
const string HW_UPDATE_USER = "hw_update_user"
const string HW_POST_EVENT = "hw_post_event"
const string HW_ADD_ORDER = "hw_add_order"
const string HW_UPDATE_ORDER = "hw_update_order"

const string SELLER_DETECT_STORE_FAULT = "seller_detect_store_fault"
const string SELLER_INITIALIZE_STORE_MONTHLY_INFO = "seller_initialize_store_monthly_info"
const string SELLER_DAILY_FAULT_3 = "seller_daily_fault_3"
const string SELLER_DAILY_FAULT_4 = "seller_daily_fault_4"
const string SELLER_DAILY_FAULT_7 = "seller_daily_fault_7"

const string INFORMATION_DAILY_DATA_UP_TO_DATE = "information_daily_date_up_to_date"
const string INFORMATION_ORDER_DATA_UP_TO_DATE = "information_order_date_up_to_date"
// order
enum OrderType {
    BATCH_ORDER = 1,
    BILL = 2,
    SALE_ORDER = 3,
    SHIP_ORDER = 4,
    SHIP_PACKAGE = 5
}

const i32 QUEUE_ERROR_TIME_SLEEP = 5

// 支付方式类别
enum SupportedPaymentMethods {
    // 在线支付
    ONLINE = 1

    // 货到付款
    COD = 2

    // 预付款
    PRE_PAID = 4
}

const i16 ACTIVITY_TYPE_NOT = 0
const i16 ACTIVITY_TYPE_FLASH = 1
const i16 ACTIVITY_TYPE_LUCKY_DRAW = 2
const i16 ACTIVITY_TYPE_REDEEM = 3
const i16 ACTIVITY_TYPE_DEAL = 4
const i16 ACTIVITY_TYPE_GROUP_BUYING = 5
const set<i16> REAL_ACTIVITY_TYPE = [ACTIVITY_TYPE_FLASH, ACTIVITY_TYPE_LUCKY_DRAW, ACTIVITY_TYPE_REDEEM]
const set<i16> SUPPORT_ACTIVITY_TYPE = [ACTIVITY_TYPE_FLASH, ACTIVITY_TYPE_REDEEM]

enum FAULT_TYPE {
    MINOR_NEGLIGENCE = 1,
    CANCEL_NEGLIGENCE_1 = 2,
    SLACK_ORDERS = 3,
    DO_NOT_PROCESS_UNTIL_CANCEL = 4,
    CANCEL_NEGLIGENCE_2 = 5,
    DELAYED_TRANSFER = 6,
    FALSE_SHIPPING = 7,
    DELAYED_DELIVERY = 8
}

const map<i16, string> FAULT_CONFIG_ID_MAP = {
1: "过失1", 2: "过失2", 3: "过失3", 4: "过失4", 5: "过失5", 6: "过失6", 7: "过失7", 8: "过失8"}

const map<i16, string> TRANSPORTATION_TIME = {
    1: '15-30',
    3: '10-20',
    5: '3-5'
}
const map<i16, i16> TRANSPORTATION_MAX_TIME = {
    1: 30,
    3: 20,
    5: 5,
    6: 30
}

const string DAYS_LOCATION = "2-5"
const i16 MAX_DAYS_LOCATION = 5

const string LOG_FORMAT = "[%(asctime)s][%(levelname)s] %(message)s"
const string DATA_TIME_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"

// region_id和时区的对应关系
const map<i16, double> REGION_HOURS = {
    1: 6.0,
    2: 8.0,
    3: 6.5,
    4: 5.0,
    5: 9.0,
    6: 3.0
}


const string SERVICE_HOST_ORDER = "order"

const map<string, map<i32, i32>> WAREHOUSE_ID_MAP = {
    "prd": {
        1: 1003,
        2: 1,
        3: 1003,
        4: 1003,
        5: 1001,
        6: 1003,
        11: 1003,
        12: 10000001,
        15: 1,  # perfee return 库区
        16: 1002,
        19: 2,
        20: 10000020,
        21: 10000021,
        25: 10000002,  # 中国刊登的商品
    },
    "test": {
        1: 1003,
        2: 1,
        3: 1003,
        4: 1003,
        5: 1001,
        6: 1003,
        11: 1003,
        12: 10000001,
        15: 1,  // perfee return 库区
        16: 1002,
        18: 10000003,
        19: 2,
        1001: 1001,
        1003: 1003,
        1002: 1002,
        13: 10000013,
        14: 10000014,
        20: 10000020,
        21: 10000021,
        22: 10000022,
        23: 10000023,
        25: 10000002,
        26: 10000026
    }
}

// dna service name
const i32 DNA_SERVICE_PORT = 8000
const string SERVICE_HOST_IDS = "ids"
